language: node_js
node_js:
- 12.13.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: fierce-ridge-20448